version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"
      devDependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "@types/*"
      - dependency-name: "eslint"
      - dependency-name: "prettier"
      - dependency-name: "husky"
      - dependency-name: "lint-staged"
      - dependency-name: "commitlint"
      - dependency-name: "@commitlint/*"
