FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.server.json ./

RUN npm install

COPY src/server ./src/server

RUN npm run build:server

EXPOSE 3001

CMD ["npm", "run", "start:server"]
